"""initial fresh

Revision ID: 89b3791550f0
Revises: 
Create Date: 2025-12-02 14:04:34.582161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b3791550f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typing_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('typing_lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_typing_lessons_lesson_number'), ['lesson_number'], unique=True)

    op.create_table('typing_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('level_index', sa.Integer(), nullable=False),
    sa.Column('global_index', sa.Integer(), nullable=False),
    sa.Column('raw_chars', sa.JSON(), nullable=True),
    sa.Column('display_chars', sa.JSON(), nullable=True),
    sa.Column('has_hand_images', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['typing_lessons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'level_index', name='uq_lesson_level_idx')
    )
    with op.batch_alter_table('typing_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_typing_levels_global_index'), ['global_index'], unique=True)
        batch_op.create_index(batch_op.f('ix_typing_levels_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('typing_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('level_index', sa.Integer(), nullable=False),
    sa.Column('global_index', sa.Integer(), nullable=False),
    sa.Column('wpm', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('mistakes', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['typing_lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'global_index', name='uq_progress_global_user')
    )
    with op.batch_alter_table('typing_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_typing_progress_global_index'), ['global_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_typing_progress_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_typing_progress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typing_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_typing_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_typing_progress_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_typing_progress_global_index'))

    op.drop_table('typing_progress')
    with op.batch_alter_table('typing_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_typing_levels_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_typing_levels_global_index'))

    op.drop_table('typing_levels')
    with op.batch_alter_table('typing_lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_typing_lessons_lesson_number'))

    op.drop_table('typing_lessons')
    # ### end Alembic commands ###
